Update

diff --git a/bin/bam2peaksV1 b/bin/bam2peaksV1
--- a/bin/bam2peaksV1
+++ b/bin/bam2peaksV1
@@ -130,7 +130,6 @@ if [ ! -d "$OUTDIR/rep0" ]; then
         mkdir $OUTDIR/rep$i
     done
     mkdir $OUTDIR/logs/
-    #mkdir $OUTDIR/fitDistr/
     mkdir $OUTDIR/$CONTROLDIR
     mkdir $OUTDIR/bw_files/
 fi
@@ -325,6 +324,7 @@ COMMENT
 ## input parameters are ready. start peak analysis
 if [ -z "$PARALLEL" ]; then
     echo -n "Predict peaks for each replicate (`date`).. "
+    PEAKFILEs=""
     ALLPEAKFILEs=""
     for(( i=0; i<${#BEDFILEa[@]}; i++ )); do
         if [ ! -d "$OUTDIR/rep$i/fitDistr/" ]; then
@@ -332,20 +332,27 @@ if [ -z "$PARALLEL" ]; then
         fi
         ID=$(echo ${BEDFILEa[$i]} | perl -ane '$_=~s/^.*\///g; $_=~s/\.gz$//g; print $_;')
 
-        reads2peaks -i ${BEDFILEa[$i]} -o $OUTDIR/rep$i/fitDistr -p $PVALUE -c $MINCLUSTERHEIGHT -e $MINBLOCKHEIGHT -x $DISTANCE -s $SCALE -g $BLOCKHEIGHT -d $DISTRIBUTION -w $MERGEDISTANCE > $OUTDIR/rep$i/$ID.allPeaks
+        reads2peaks -i ${BEDFILEa[$i]} -o $OUTDIR/rep$i/fitDistr -p $PVALUE -c $MINCLUSTERHEIGHT -e $MINBLOCKHEIGHT -x $DISTANCE -s $SCALE -g $BLOCKHEIGHT -d $DISTRIBUTION -w $MERGEDISTANCE > $OUTDIR/rep$i/$ID.peaks
 
+        PEAKFILEs="$PEAKFILEs,$OUTDIR/rep$i/$ID.peaks"
+
+        ## now also analyze peaks which are above threshold pvalue ($PVALUE), however are <0.2
+        #intersectBed -a <(cat $OUTDIR/$i/fitDistr/INPUT.BG.P_VALUE | perl -ane 'if($F[6]<1) { print "$F[1]\t$F[2]\t$F[3]\t$F[4]\t$F[0]\t.\tN\n"; }') -b $OUTDIR/rep$i/$ID.peaks -v | sortBed -i stdin | bedtools merge -c 4,5,6,7 -o distinct,sum,distinct,distinct -d $MERGEDISTANCE > $OUTDIR/rep$i/$ID.allPeaks
+        cat $OUTDIR/$i/fitDistr/INPUT.BG.P_VALUE | perl -ane 'print "$F[1]\t$F[2]\t$F[3]\t$F[4]\t$F[0]\t.\tA\n";' | sortBed -i stdin | bedtools merge -c 4,5,6,7 -o distinct,sum,distinct,distinct -d $MERGEDISTANCE > $OUTDIR/rep$i/$ID.allPeaks
         ALLPEAKFILEs="$ALLPEAKFILEs,$OUTDIR/rep$i/$ID.allPeaks"
     done
     echo "done"
+    PEAKFILEs=$(echo $PEAKFILEs | perl -ane '$_=~s/^\,//g; print $_;')
     ALLPEAKFILEs=$(echo $ALLPEAKFILEs | perl -ane '$_=~s/^\,//g; print $_;')
 
     if [ ${#BEDFILEa[@]} -gt 1 ]; then
         echo -n "Determine common peaks between replicates (`date`).. "
-        #multiIntersectBed.sh -i $ALLPEAKFILEs | perl -ane 'if($F[3]>=2) { print $_; }' | cut -f 1-3 | bed2expr -i stdin -j $BAMFILEs -d -g $GENOME | perl -ane 'print "$F[0]\t$F[1]\t$F[2]\t$F[0]:$F[1]-$F[2]\t"; $sum=0; $count=0; foreach(@F[3..scalar(@F)-1]) { $sum+=$_; $count++; } $mean=sprintf("%d", $sum/$count); print "$sum\t.\tA\n";' | sort -k 1,1 -k 2n,2 -k 3n,3 > $OUTDIR/ALLPEAKS.BED
-        ALLPEAKFILEs=$(echo $ALLPEAKFILEs | perl -ane '$_=~s/\,/ /g; print $_;')
-        cat <(grep -w Y $ALLPEAKFILEs | sortBed -i stdin | bedtools merge -c 4,5,6,7,8,4 -o distinct,sum,distinct,mean,distinct,count) <(grep -wv Y $ALLPEAKFILEs | sortBed -i stdin | bedtools merge -c 4,5,6,7,8,4 -o distinct,sum,distinct,mean,distinct,count) | perl -ane 'if($F[8]>=2) { print $_; } else { print "$F[0]\t$F[1]\t$F[2]\t$F[3]\t$F[4]\t$F[5]\t$F[6]\tN\t$F[8]\n"; }' | cut -f 1-8 > $OUTDIR/ALLPEAKS.BED
+        multiIntersectBed.sh -i $PEAKFILEs | perl -ane 'if($F[3]>=2) { print $_; }' | cut -f 1-3 | bed2expr -i stdin -j $BAMFILEs -d -g $GENOME | perl -ane 'print "$F[0]\t$F[1]\t$F[2]\t$F[0]:$F[1]-$F[2]\t"; $sum=0; $count=0; foreach(@F[3..scalar(@F)-1]) { $sum+=$_; $count++; } $mean=sprintf("%d", $sum/$count); print "$mean\t.\tY\n";' | sort -k 1,1 -k 2n,2 -k 3n,3 > $OUTDIR/PEAKS.BED
+        multiIntersectBed.sh -i $ALLPEAKFILEs | perl -ane 'if($F[3]>=2) { print $_; }' | cut -f 1-3 | bed2expr -i stdin -j $BAMFILEs -d -g $GENOME | perl -ane 'print "$F[0]\t$F[1]\t$F[2]\t$F[0]:$F[1]-$F[2]\t"; $sum=0; $count=0; foreach(@F[3..scalar(@F)-1]) { $sum+=$_; $count++; } $mean=sprintf("%d", $sum/$count); print "$mean\t.\tA\n";' | sort -k 1,1 -k 2n,2 -k 3n,3 > $OUTDIR/ALLPEAKS.BED
         echo "done"
     else
+        ID=`echo $BEDFILEs | perl -ane '$_=~s/^.*\///g; $_=~s/Rep.*$//g; $_=~s/\_$//g; print $_;'`;
+        scp $OUTDIR/rep0/$ID.peaks $OUTDIR/PEAKS.BED
         scp $OUTDIR/rep0/$ID.allPeaks $OUTDIR/ALLPEAKS.BED
     fi
 else
@@ -378,29 +385,43 @@ else
     done
     echo "done"
 
+    PEAKFILEs=""
     ALLPEAKFILEs=""
     echo -n "Merge all block groups files into one, and predict peaks (`date`).. "
     for(( i=0; i<${#BEDFILEa[@]}; i++ )); do
         ID=$(echo ${BEDFILEa[$i]} | perl -ane '$_=~s/^.*\///g; $_=~s/\.gz$//g; print $_;')
-        bg2peaks -i $OUTDIR/rep$i/fitDistr/INPUT.BG -o $OUTDIR/rep$i/fitDistr -p $PVALUE -d $DISTRIBUTION -w $MERGEDISTANCE > $OUTDIR/rep$i/$ID.allPeaks
+        bg2peaks -i $OUTDIR/rep$i/fitDistr/INPUT.BG -o $OUTDIR/rep$i/fitDistr -p $PVALUE -d $DISTRIBUTION -w $MERGEDISTANCE > $OUTDIR/rep$i/$ID.peaks
 
+        PEAKFILEs="$PEAKFILEs,$OUTDIR/rep$i/$ID.peaks"
+
+        ## now also analyze peaks which are above threshold pvalue ($PVALUE), however are <0.2
+        #intersectBed -a <(cat $OUTDIR/rep$i/fitDistr/INPUT.BG.P_VALUE | perl -ane 'if($F[6]<0.2) { print "$F[1]\t$F[2]\t$F[3]\t$F[4]\t$F[0]\t.\tN\n"; }') -b $OUTDIR/rep$i/$ID.peaks -v | sortBed -i stdin | bedtools merge -c 4,5,6,7 -o distinct,sum,distinct,distinct -d $MERGEDISTANCE > $OUTDIR/rep$i/$ID.allPeaks
+        cat $OUTDIR/rep$i/fitDistr/INPUT.BG.P_VALUE | perl -ane 'print "$F[1]\t$F[2]\t$F[3]\t$F[4]\t$F[0]\t.\tA\n";' | sortBed -i stdin | bedtools merge -c 4,5,6,7 -o distinct,sum,distinct,distinct -d $MERGEDISTANCE > $OUTDIR/rep$i/$ID.allPeaks
         ALLPEAKFILEs="$ALLPEAKFILEs,$OUTDIR/rep$i/$ID.allPeaks"
     done
     echo "done"
+    PEAKFILEs=$(echo $PEAKFILEs | perl -ane '$_=~s/^\,//g; print $_;')
     ALLPEAKFILEs=$(echo $ALLPEAKFILEs | perl -ane '$_=~s/^\,//g; print $_;')
 
     if [ ${#BEDFILEa[@]} -gt 1 ]; then
         echo -n "Determine common peaks between replicates (`date`).. "
-        #multiIntersectBed.sh -i $ALLPEAKFILEs | perl -ane 'if($F[3]>=2) { print $_; }' | cut -f 1-3 | bed2expr -i stdin -j $BAMFILEs -d -g $GENOME | perl -ane 'print "$F[0]\t$F[1]\t$F[2]\t$F[0]:$F[1]-$F[2]\t"; $sum=0; $count=0; foreach(@F[3..scalar(@F)-1]) { $sum+=$_; $count++; } $mean=sprintf("%d", $sum/$count); print "$sum\t.\tA\n";' | sort -k 1,1 -k 2n,2 -k 3n,3 > $OUTDIR/ALLPEAKS.BED
-        ALLPEAKFILEs=$(echo $ALLPEAKFILEs | perl -ane '$_=~s/\,/ /g; print $_;')
-        cat <(grep -w Y $ALLPEAKFILEs | sortBed -i stdin | bedtools merge -c 4,5,6,7,8,4 -o distinct,sum,distinct,mean,distinct,count) <(grep -wv Y $ALLPEAKFILEs | sortBed -i stdin | bedtools merge -c 4,5,6,7,8,4 -o distinct,sum,distinct,mean,distinct,count) | perl -ane 'if($F[8]>=2) { print $_; } else { print "$F[0]\t$F[1]\t$F[2]\t$F[3]\t$F[4]\t$F[5]\t$F[6]\tN\t$F[8]\n"; }' | cut -f 1-8 > $OUTDIR/ALLPEAKS.BED
+        ID=`echo $BEDFILEs | perl -ane '$_=~s/^.*\///g; $_=~s/Rep.*$//g; $_=~s/\_$//g; print $_;'`;
+        multiIntersectBed.sh -i $PEAKFILEs | perl -ane 'if($F[3]>=2) { print $_; }' | cut -f 1-3 | bed2expr -i stdin -j $BAMFILEs -d -g $GENOME | perl -ane 'print "$F[0]\t$F[1]\t$F[2]\t$F[0]:$F[1]-$F[2]\t"; $sum=0; $count=0; foreach(@F[3..scalar(@F)-1]) { $sum+=$_; $count++; } $mean=sprintf("%d", $sum/$count); print "$mean\t.\tY\n";' | sort -k 1,1 -k 2n,2 -k 3n,3 > $OUTDIR/PEAKS.BED
+        multiIntersectBed.sh -i $ALLPEAKFILEs | perl -ane 'if($F[3]>=2) { print $_; }' | cut -f 1-3 | bed2expr -i stdin -j $BAMFILEs -d -g $GENOME | perl -ane 'print "$F[0]\t$F[1]\t$F[2]\t$F[0]:$F[1]-$F[2]\t"; $sum=0; $count=0; foreach(@F[3..scalar(@F)-1]) { $sum+=$_; $count++; } $mean=sprintf("%d", $sum/$count); print "$mean\t.\tA\n";' | sort -k 1,1 -k 2n,2 -k 3n,3 > $OUTDIR/ALLPEAKS.BED
         echo "done"
     else
+        scp $OUTDIR/rep0/$ID.peaks $OUTDIR/PEAKS.BED
         scp $OUTDIR/rep0/$ID.allPeaks $OUTDIR/ALLPEAKS.BED
     fi
 fi
 
 echo -n "Check if peak file is created properly (`date`).. "
+if [ ! -s "$OUTDIR/PEAKS.BED" ]; then
+    echo
+    echo "Error: file $OUTDIR/PEAKS.BED not created properly"
+    exit 1
+fi
+
 if [ ! -s "$OUTDIR/ALLPEAKS.BED" ]; then
     echo
     echo "Error: file $OUTDIR/ALLPEAKS.BED not created properly"
@@ -448,17 +469,23 @@ if [ ! -z "$CONTROLFILEs" ]; then
     cat $CONTROLBEDFILEx | sort -k 1,1 -k 2n,2 -k 3n,3 > $OUTDIR/$CONTROLDIR/$ID.bed
 
     echo -n "Predict peaks for control replicate (`date`).. "
-    reads2peaks -i $OUTDIR/$CONTROLDIR/$ID.bed -o $OUTDIR/$CONTROLDIR/fitDistr -p $PVALUE -c $MINCLUSTERHEIGHT -e $MINBLOCKHEIGHT -x $DISTANCE -s $SCALE -g $BLOCKHEIGHT -d $DISTRIBUTION -w $MERGEDISTANCE | grep -w Y > $OUTDIR/$CONTROLDIR/$ID.allPeaks
+    reads2peaks -i $OUTDIR/$CONTROLDIR/$ID.bed -o $OUTDIR/$CONTROLDIR/fitDistr -p $PVALUE -c $MINCLUSTERHEIGHT -e $MINBLOCKHEIGHT -x $DISTANCE -s $SCALE -g $BLOCKHEIGHT -d $DISTRIBUTION -w $MERGEDISTANCE > $OUTDIR/$CONTROLDIR/$ID.peaks
     echo "done"
 
     ## check if control peak file is computed properly
-    if [ -s "$OUTDIR/$CONTROLDIR/$ID.allPeaks" ]; then
+    if [ -s "$OUTDIR/$CONTROLDIR/$ID.peaks" ]; then
         TMP=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
+        intersectBed -a $OUTDIR/PEAKS.BED -b $OUTDIR/$CONTROLDIR/$ID.peaks -v > $TMP
+        mv $TMP $OUTDIR/PEAKS.BED
+
+        ## now also analyze peaks which are above threshold pvalue ($PVALUE), however are <0.2
+        #intersectBed -a <(cat $OUTDIR/$CONTROLDIR/fitDistr/INPUT.BG.P_VALUE | perl -ane 'if($F[6]<1) { print "$F[1]\t$F[2]\t$F[3]\t$F[4]\t$F[0]\t.\tN\n"; }') -b $OUTDIR/$CONTROLDIR/$ID.peaks -v | sortBed -i stdin | bedtools merge -c 4,5,6,7 -o distinct,sum,distinct,distinct -d $MERGEDISTANCE > $OUTDIR/$CONTROLDIR/$ID.allPeaks
+        cat $OUTDIR/$CONTROLDIR/fitDistr/INPUT.BG.P_VALUE | perl -ane 'print "$F[1]\t$F[2]\t$F[3]\t$F[4]\t$F[0]\t.\tN\n"; }' | sortBed -i stdin | bedtools merge -c 4,5,6,7 -o distinct,sum,distinct,distinct -d $MERGEDISTANCE > $OUTDIR/$CONTROLDIR/$ID.allPeaks
         intersectBed -a $OUTDIR/ALLPEAKS.BED -b $OUTDIR/$CONTROLDIR/$ID.allPeaks -v > $TMP
         mv $TMP $OUTDIR/ALLPEAKS.BED
     else
         echo
-        echo "Error: control peak file $OUTDIR/$CONTROLDIR/$ID.allPeaks not created properly"
+        echo "Error: control peak file $OUTDIR/$CONTROLDIR/$ID.peaks not created properly"
         exit 1
     fi
 fi
@@ -466,16 +493,12 @@ echo "done"
 
 echo -n "Remove peaks overlapping with blacklisted regions (`date`).. "
 TMP=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
+intersectBed -a $OUTDIR/PEAKS.BED -b $GENOME_BLACKLIST -v > $TMP
+mv $TMP $OUTDIR/PEAKS.BED
+
 intersectBed -a $OUTDIR/ALLPEAKS.BED -b $GENOME_BLACKLIST -v > $TMP
 mv $TMP $OUTDIR/ALLPEAKS.BED
-grep -w Y $OUTDIR/ALLPEAKS.BED > $OUTDIR/PEAKS.BED
 echo "done"
-
-#echo -n "Recompute significance level of peaks (`date`).. "
-#perl -ane 'print "$F[4]\t$F[0]\t$F[1]\t$F[2]\t$F[3]\t$F[5]\n";' $OUTDIR/ALLPEAKS.BED | $FINDNFRPATH/share/R/fitDistr.R -i stdin -o $OUTDIR/fitDistr/ALLPEAKS.BED.P_VALUE -d $DISTRIBUTION 2>&1>/dev/null
-#cat $OUTDIR/fitDistr/ALLPEAKS.BED.P_VALUE | perl -ane 'print "$F[1]\t$F[2]\t$F[3]\t$F[4]\t$F[0]\t.\t$F[6]\n";' > $OUTDIR/ALLPEAKS.BED
-#cat $OUTDIR/ALLPEAKS.BED | perl -ane 'if($F[6]<'$PVALUE') { print $_; }' > $OUTDIR/PEAKS.BED
-#echo "done"
 
 echo -n "Compute normalized peak scores (`date`).. "
 TMP=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
@@ -496,7 +519,7 @@ if [ ! -z "$BROAD" ]; then
     fi
 
     echo -n "Remove broad peaks overlapping with blacklisted regions (`date`).. "
-    intersectBed -a $OUTDIR/peaks_broad/peaks.merged -b $GENOME_BLACKLIST -v > $OUTDIR/BROADPEAKS.BED
+    intersectBed -a $OUTDIR/peaks_broad/peaks.merged -b $GENOME_BLACKLIST -v | perl -ane 'print "$F[0]\t$F[1]\t$F[2]\t$F[0]:$F[1]-$F[2]\t$F[3]\t.\tY\n";' > $OUTDIR/BROADPEAKS.BED
     echo "done"
 
     echo -n "Compute normalized peak scores (`date`).. "
